// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgxsfmukamxfggdxpyhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndneHNmbXVrYW14ZmdnZHhweWhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjA5NzcsImV4cCI6MjA2MTQzNjk3N30.50tkKwAlKlMc_QwjzBzCJYrIi4l6Og4W7M6OpFFh4Dg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);